// Generated by gencpp from file server_interface/LockOn.msg
// DO NOT EDIT!


#ifndef SERVER_INTERFACE_MESSAGE_LOCKON_H
#define SERVER_INTERFACE_MESSAGE_LOCKON_H

#include <ros/service_traits.h>


#include <server_interface/LockOnRequest.h>
#include <server_interface/LockOnResponse.h>


namespace server_interface
{

struct LockOn
{

typedef LockOnRequest Request;
typedef LockOnResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct LockOn
} // namespace server_interface


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::server_interface::LockOn > {
  static const char* value()
  {
    return "685ca96bd6cc7d98e3174f48c9825cf9";
  }

  static const char* value(const ::server_interface::LockOn&) { return value(); }
};

template<>
struct DataType< ::server_interface::LockOn > {
  static const char* value()
  {
    return "server_interface/LockOn";
  }

  static const char* value(const ::server_interface::LockOn&) { return value(); }
};


// service_traits::MD5Sum< ::server_interface::LockOnRequest> should match
// service_traits::MD5Sum< ::server_interface::LockOn >
template<>
struct MD5Sum< ::server_interface::LockOnRequest>
{
  static const char* value()
  {
    return MD5Sum< ::server_interface::LockOn >::value();
  }
  static const char* value(const ::server_interface::LockOnRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::server_interface::LockOnRequest> should match
// service_traits::DataType< ::server_interface::LockOn >
template<>
struct DataType< ::server_interface::LockOnRequest>
{
  static const char* value()
  {
    return DataType< ::server_interface::LockOn >::value();
  }
  static const char* value(const ::server_interface::LockOnRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::server_interface::LockOnResponse> should match
// service_traits::MD5Sum< ::server_interface::LockOn >
template<>
struct MD5Sum< ::server_interface::LockOnResponse>
{
  static const char* value()
  {
    return MD5Sum< ::server_interface::LockOn >::value();
  }
  static const char* value(const ::server_interface::LockOnResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::server_interface::LockOnResponse> should match
// service_traits::DataType< ::server_interface::LockOn >
template<>
struct DataType< ::server_interface::LockOnResponse>
{
  static const char* value()
  {
    return DataType< ::server_interface::LockOn >::value();
  }
  static const char* value(const ::server_interface::LockOnResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SERVER_INTERFACE_MESSAGE_LOCKON_H
