// Generated by gencpp from file server_interface/SubmitKamikazeRequest.msg
// DO NOT EDIT!


#ifndef SERVER_INTERFACE_MESSAGE_SUBMITKAMIKAZEREQUEST_H
#define SERVER_INTERFACE_MESSAGE_SUBMITKAMIKAZEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace server_interface
{
template <class ContainerAllocator>
struct SubmitKamikazeRequest_
{
  typedef SubmitKamikazeRequest_<ContainerAllocator> Type;

  SubmitKamikazeRequest_()
    : text()  {
    }
  SubmitKamikazeRequest_(const ContainerAllocator& _alloc)
    : text(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _text_type;
  _text_type text;





  typedef boost::shared_ptr< ::server_interface::SubmitKamikazeRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::server_interface::SubmitKamikazeRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SubmitKamikazeRequest_

typedef ::server_interface::SubmitKamikazeRequest_<std::allocator<void> > SubmitKamikazeRequest;

typedef boost::shared_ptr< ::server_interface::SubmitKamikazeRequest > SubmitKamikazeRequestPtr;
typedef boost::shared_ptr< ::server_interface::SubmitKamikazeRequest const> SubmitKamikazeRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::server_interface::SubmitKamikazeRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::server_interface::SubmitKamikazeRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::server_interface::SubmitKamikazeRequest_<ContainerAllocator1> & lhs, const ::server_interface::SubmitKamikazeRequest_<ContainerAllocator2> & rhs)
{
  return lhs.text == rhs.text;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::server_interface::SubmitKamikazeRequest_<ContainerAllocator1> & lhs, const ::server_interface::SubmitKamikazeRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace server_interface

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::server_interface::SubmitKamikazeRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::server_interface::SubmitKamikazeRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::server_interface::SubmitKamikazeRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::server_interface::SubmitKamikazeRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::server_interface::SubmitKamikazeRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::server_interface::SubmitKamikazeRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::server_interface::SubmitKamikazeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "74697ed3d931f6eede8bf3a8dfeca160";
  }

  static const char* value(const ::server_interface::SubmitKamikazeRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x74697ed3d931f6eeULL;
  static const uint64_t static_value2 = 0xde8bf3a8dfeca160ULL;
};

template<class ContainerAllocator>
struct DataType< ::server_interface::SubmitKamikazeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "server_interface/SubmitKamikazeRequest";
  }

  static const char* value(const ::server_interface::SubmitKamikazeRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::server_interface::SubmitKamikazeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string text\n"
;
  }

  static const char* value(const ::server_interface::SubmitKamikazeRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::server_interface::SubmitKamikazeRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.text);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SubmitKamikazeRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::server_interface::SubmitKamikazeRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::server_interface::SubmitKamikazeRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "text: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.text);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SERVER_INTERFACE_MESSAGE_SUBMITKAMIKAZEREQUEST_H
