// Generated by gencpp from file server_interface/SubmitKamikaze.msg
// DO NOT EDIT!


#ifndef SERVER_INTERFACE_MESSAGE_SUBMITKAMIKAZE_H
#define SERVER_INTERFACE_MESSAGE_SUBMITKAMIKAZE_H

#include <ros/service_traits.h>


#include <server_interface/SubmitKamikazeRequest.h>
#include <server_interface/SubmitKamikazeResponse.h>


namespace server_interface
{

struct SubmitKamikaze
{

typedef SubmitKamikazeRequest Request;
typedef SubmitKamikazeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SubmitKamikaze
} // namespace server_interface


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::server_interface::SubmitKamikaze > {
  static const char* value()
  {
    return "191f0a61ba3a929ce6cac14343f74651";
  }

  static const char* value(const ::server_interface::SubmitKamikaze&) { return value(); }
};

template<>
struct DataType< ::server_interface::SubmitKamikaze > {
  static const char* value()
  {
    return "server_interface/SubmitKamikaze";
  }

  static const char* value(const ::server_interface::SubmitKamikaze&) { return value(); }
};


// service_traits::MD5Sum< ::server_interface::SubmitKamikazeRequest> should match
// service_traits::MD5Sum< ::server_interface::SubmitKamikaze >
template<>
struct MD5Sum< ::server_interface::SubmitKamikazeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::server_interface::SubmitKamikaze >::value();
  }
  static const char* value(const ::server_interface::SubmitKamikazeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::server_interface::SubmitKamikazeRequest> should match
// service_traits::DataType< ::server_interface::SubmitKamikaze >
template<>
struct DataType< ::server_interface::SubmitKamikazeRequest>
{
  static const char* value()
  {
    return DataType< ::server_interface::SubmitKamikaze >::value();
  }
  static const char* value(const ::server_interface::SubmitKamikazeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::server_interface::SubmitKamikazeResponse> should match
// service_traits::MD5Sum< ::server_interface::SubmitKamikaze >
template<>
struct MD5Sum< ::server_interface::SubmitKamikazeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::server_interface::SubmitKamikaze >::value();
  }
  static const char* value(const ::server_interface::SubmitKamikazeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::server_interface::SubmitKamikazeResponse> should match
// service_traits::DataType< ::server_interface::SubmitKamikaze >
template<>
struct DataType< ::server_interface::SubmitKamikazeResponse>
{
  static const char* value()
  {
    return DataType< ::server_interface::SubmitKamikaze >::value();
  }
  static const char* value(const ::server_interface::SubmitKamikazeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SERVER_INTERFACE_MESSAGE_SUBMITKAMIKAZE_H
